### ISSUE TITLE
Enable/Disable auto scrolling when message is being streamed 

### ISSUE THREAD

**Issue by seonWKim** [seonWKim/ai-sidebar#117]
### Describe the feature you want to request

Add feature to allow users enable/disable scrolling 

### Describe how you want to implement the feature

- Add configuration settings in the `Settings.vue` 
- Store the value in chrome local storage so that users configuration can be retained

**Comment by Vayras** [comment]
hi @seonwoo960000  I would like to work on this issue, Can you Please assign me this issue?

**Comment by seonwoo960000** [comment]
@Vayras sure, it all yours ~

**Comment by seonWKim** [comment]
Hi @Vayras, I've added a PR related to this issue. 🙏
